[build]
  # Static site deployment
  command = "echo 'Static site - no build required'"
  publish = "."

# Performance optimizations - Simplified
[[headers]]
  for = "/*"
  [headers.values]
    # Cache static assets
    Cache-Control = "public, max-age=3600"
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.html"
  [headers.values]
    # HTML files - shorter cache
    Cache-Control = "public, max-age=1800"

[[headers]]
  for = "*.css"
  [headers.values]
    # CSS files - longer cache
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.js"
  [headers.values]
    # JavaScript files - longer cache
    Cache-Control = "public, max-age=86400"

# Force HTTPS redirect
[[redirects]]
  from = "http://afiyaindia.com/*"
  to = "https://afiyaindia.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.afiyaindia.com/*"
  to = "https://www.afiyaindia.com/:splat"
  status = 301
  force = true

# Redirect www to non-www for better performance
[[redirects]]
  from = "https://www.afiyaindia.com/*"
  to = "https://afiyaindia.com/:splat"
  status = 301
  force = true

# Optional: Set up redirects for better SEO
[[redirects]]
  from = "/patient-reviews"
  to = "/patient-reviews.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog-fixed.html"
  status = 200

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404